### ISSUE TITLE
Wrap FFTNormalizedCorrelationImageFilter

### ISSUE THREAD

**Issue by thewtex** [BlueQuartzSoftware/ITKImageProcessing#111]
https://itk.org/Doxygen/html/classitk_1_1FFTNormalizedCorrelationImageFilter.html

**Comment by fbudin69500** [comment]
See https://github.com/BlueQuartzSoftware/ITKImageProcessing/pull/126

**Comment by fbudin69500** [comment]
Merged in https://github.com/BlueQuartzSoftware/ITKImageProcessing/commit/4d928f2ca64ce1b2002ae3523d4edbe624732cc9
