### ISSUE TITLE
ITK::RGB To Luminance output component dimensions

### ISSUE THREAD

**Issue by thewtex** [BlueQuartzSoftware/ITKImageProcessing#114]
Is currently 4. Should be 1.

**Comment by thewtex** [comment]
@fbudin69500 I have verified that the pixel type is scalar and cDims[0] == 1 when transfering the output in the filter() stage here:

  https://github.com/BlueQuartzSoftware/ITKImageProcessing/blob/e1ea211f93d4a08e651fddd352f7307a7cd0f534/ITKImageProcessingFilters/itkInPlaceImageToDream3DDataFilter.hxx#L123

It looks like this issue is related to this comment:

  https://github.com/BlueQuartzSoftware/ITKImageProcessing/blob/e1ea211f93d4a08e651fddd352f7307a7cd0f534/ITKImageProcessingFilters/itkInPlaceImageToDream3DDataFilter.hxx#L174

Working on a patch...

**Comment by fbudin69500** [comment]
Just created a PR :)

**Comment by fbudin69500** [comment]
See https://github.com/BlueQuartzSoftware/ITKImageProcessing/pull/118
