### ISSUE TITLE
ITK::Image Writer (KW) does not handle RGB and does not warn about this during preflight

### ISSUE THREAD

**Issue by imikejackson** [BlueQuartzSoftware/ITKImageProcessing#116]
Would it be possible for the writer to handle RGB?

**Comment by fbudin69500** [comment]
I thought all RGB images were opened as RGBA in DREAM3D, which is why the writer only supports RGBA right now. How do you open an RGB image as RGB? (ITK::Image Reader is set up to open all RGB images as RGBA images)

**Comment by imikejackson** [comment]
our "IPF Colors" filter generates an RGB array. I can around it by adding an alpha channel to the data, but it would be nice if the preflight warns when there are only 3 channels on the input.

**Comment by imikejackson** [comment]
I guess I could also add an option on the IPF Colors filter to generate an alpha channel.

**Comment by thewtex** [comment]
This patch may address at least part of the issue:

  https://github.com/BlueQuartzSoftware/ITKImageProcessing/pull/115/commits/dad1a53a40a59d46693203458f1752c473fde1cd

**Comment by fbudin69500** [comment]
@imikejackson I can work on it. I didn't know RGB was used in DREAM3D
@thewtex : yes indeed, it does solve part of the problem .The other part is in "The Macro". I'll look at it now.
