### ISSUE TITLE
CircleCI is timing out

### ISSUE THREAD

**Issue by thewtex** [BlueQuartzSoftware/ITKImageProcessing#129]

**Comment by thewtex** [comment]
I am investigating a change to CMAKE_BUILD_TYPE.

**Comment by fbudin69500** [comment]
Using -Ofast instead of -O3 or -O2?

**Comment by thewtex** [comment]
CMAKE_BUILD_TYPE=MinSizeRel

**Comment by fbudin69500** [comment]
Yes, that should already help, as -Os should be faster than any of -O2 or -O3. I am running some tests on my machine with -Ofast to see if that helps also.
