### ISSUE TITLE
ITKApproximateSignedDistanceMapImage Test fails

### ISSUE THREAD

**Issue by imikejackson** [BlueQuartzSoftware/ITKImageProcessing#148]
The test fails due to differences in the filter between ITK 4.11 and 4.12

**Comment by imikejackson** [comment]
![screen shot 2017-09-28 at 11 22 50 am](https://user-images.githubusercontent.com/5182396/30978430-8318c24e-a448-11e7-846e-340c511d451d.png)

**Comment by fbudin69500** [comment]
@imikejackson Could you let me know the configuration of the machine on which this test fails? I cannot reproduce it locally.

**Comment by imikejackson** [comment]
Hmm, Now it seems to be working? the different was between ITK 4.11 and 4.12 on all platforms. But now it seems that everything is passing? Odd.

**Comment by fbudin69500** [comment]
Odd indeed. Closing this issue for now then.
