### ISSUE TITLE
PR #150 Causes filters to ignore "SaveAsNewArray" filter parameter

### ISSUE THREAD

**Issue by imikejackson** [BlueQuartzSoftware/ITKImageProcessing#152]

**Comment by fbudin69500** [comment]
Does https://github.com/BlueQuartzSoftware/ITKImageProcessing/commit/d7db85f333ebbd1d290aacddf7a5d53cd1e1a104 fix this issue?

**Comment by imikejackson** [comment]
Seems to. Doing a full compile to check some of the other filters.

**Comment by fbudin69500** [comment]
Thanks for solving the issue!
