### ISSUE TITLE
Linker Error with OS X 10.10 and Clang with ITKImageProcessingWriter

### ISSUE THREAD

**Issue by imikejackson** [BlueQuartzSoftware/ITKImageProcessing#16]
I am getting the following linker error with the latest codes:

Undefined symbols for architecture x86_64:
  "typeinfo for ITKImageWriter", referenced from:
      ITKImageProcessingWriterTest::TestWriteImage(QString const&, std::__1::shared_ptr<DataContainerArray>, DataArrayPath&, QByteArray const&) in ITKImageProcessingUnitTest.cpp.o

This is with OS X 10.10.5, Xcode 7.2

@thewtex Can you or one of the ITK engineers on the task take a look?

**Comment by thewtex** [comment]
@imikejackson Thanks for the note.  Will look into it.

Any other suggestions on versions of DREAM.3D / dependencies to reproduce the build environment?

**Comment by imikejackson** [comment]
Latest develop branch on DREAM.3D/SIMPL/SIMPLView. We also use this bit of cmake code.

  set(CMAKE_CXX_FLAGS "-stdlib=libc++ -std=c++11 -Wmost -Wno-four-char-constants -Wno-unknown-pragmas -mfpmath=sse" CACHE STRING "" FORCE)

We are also using ITK 4.9.1 for development.

**Comment by fbudin69500** [comment]
Closing as this issue has been resolved in https://github.com/BlueQuartzSoftware/ITKImageProcessing/pull/18
