### ISSUE TITLE
MSVC error C2899: typename cannot be used outside a template declaration

### ISSUE THREAD

**Issue by sdonegan** [BlueQuartzSoftware/ITKImageProcessing#37]
Some of the auto-generated filters produce this compile error on MSVC12.  A specific example is the ITKSumProjectionImage filter at lines 102 and 127, when declaring the type in the Dream3dArraySwitchMacroOutputType macro.

**Comment by imikejackson** [comment]
http://my.cdash.org/viewBuildError.php?buildid=1099019

shows the build errors.

**Comment by fbudin69500** [comment]
I was able to reproduce the bug. I will submit a patch to correct this problem. Thanks for reporting it.
