### ISSUE TITLE
Wrap itk::AdaptiveHistogramEqualizationImageFilter

### ISSUE THREAD

**Issue by thewtex** [BlueQuartzSoftware/ITKImageProcessing#49]
https://itk.org/Doxygen/html/classitk_1_1AdaptiveHistogramEqualizationImageFilter.html

@fbudin69500 is this one easy with your scripts?

**Comment by fbudin69500** [comment]
The Python script generates cpp code, but that does not compile. Checking to see if it is easily fixable.

**Comment by fbudin69500** [comment]
The filter compiles. I still have to work on the tests.
Work in progress [here](https://github.com/fbudin69500/ITKImageProcessing/commit/7c24467043f826c26949057188bde5bb665fc38c)

**Comment by thewtex** [comment]
@fbudin69500 nice, thanks!

**Comment by fbudin69500** [comment]
See [PR](https://github.com/BlueQuartzSoftware/ITKImageProcessing/pull/55)
