### ISSUE TITLE
Provide instructions in error message on what to do when filter does not work with RGB / Vector

### ISSUE THREAD

**Issue by thewtex** [BlueQuartzSoftware/ITKImageProcessing#60]

**Comment by imikejackson** [comment]
Is this just a general comment for ALL the ITKImageProcessing filters or a specific one?

**Comment by thewtex** [comment]
There are some filters that only work with scalar pixel types. They should already throw an error, but we want to give DREAM.3D users a concrete suggestion on what filter to use to address the issue.

**Comment by imikejackson** [comment]
Sounds good. I just renamed the Processing/FlattenImage to Processing/ConvertRgbToGrayScale in the main DREAM.3D repo.

**Comment by thewtex** [comment]
@imikejackson Great. Thanks for the note.

**Comment by fbudin69500** [comment]
@thewtex As soon as the [RGBToLuminance](https://github.com/BlueQuartzSoftware/ITKImageProcessing/pull/84) filter is merged, I will go ahead and update these error messages [1](https://github.com/BlueQuartzSoftware/ITKImageProcessing/blob/develop/ITKImageProcessingFilters/Dream3DTemplateAliasMacro.h#L264),[2](https://github.com/BlueQuartzSoftware/ITKImageProcessing/blob/develop/ITKImageProcessingFilters/Dream3DTemplateAliasMacro.h#L264) to point the user towards RGBToLuminance and RGBToLuminance
