### ISSUE TITLE
Wrap itk::MorphologicalWatershedImageFilter

### ISSUE THREAD

**Issue by thewtex** [BlueQuartzSoftware/ITKImageProcessing#88]
https://itk.org/Doxygen/html/classitk_1_1MorphologicalWatershedImageFilter.html

**Comment by thewtex** [comment]
Issue #94

**Comment by fbudin69500** [comment]
Merged in https://github.com/BlueQuartzSoftware/ITKImageProcessing/commit/f5fb9251a2a6e5c67795c3394cb2091da697245e
