### ISSUE TITLE
Add ImageIOs to ITKImageReader

### ISSUE THREAD

**Issue by johan-andruejol** [BlueQuartzSoftware/ITKImageProcessing#9]
Right now, only PNG and SCIFIO are registered as factories. It would be good to add all the other formats

Also make sure that SCIFIO is registered first.

**Comment by thewtex** [comment]
I believe this is addressed in master.  In not, please re-open.

**Comment by fbudin69500** [comment]
There are still some issues to be addressed for this (currently ITK file reader relies both on the automatic registration and manual registration in the factory). Reopening this issue.

**Comment by fbudin69500** [comment]
This issue has been solved in https://github.com/BlueQuartzSoftware/ITKImageProcessing/pull/21
