### ISSUE TITLE
Wrap itk::VectorRescaleIntensityImageeFilter

### ISSUE THREAD

**Issue by thewtex** [BlueQuartzSoftware/ITKImageProcessing#96]
https://itk.org/Doxygen/html/classitk_1_1VectorRescaleIntensityImageFilter.html

**Comment by fbudin69500** [comment]
This one is not in SimpleITK...

**Comment by fbudin69500** [comment]
See https://github.com/BlueQuartzSoftware/ITKImageProcessing/pull/137

**Comment by fbudin69500** [comment]
Merged in https://github.com/BlueQuartzSoftware/ITKImageProcessing/pull/137
